# FIXME: ケバブケースに置き換える
# FIXME: module を使用する

[versions]
androidGradlePlugin = "8.5.0"
androidx-browser = "1.8.0"
androidxComposeBom = "2024.06.00"
androidxComposeCompiler = "1.5.14"
androidxEspresso = "3.6.0"
androidxHilt = "1.2.0"
androidxLifecycle = "2.8.2"
androidxNavigation = "2.8.0-beta06"
androidxTestExt = "1.2.0"
coil = "2.6.0"
compileSdk = "34"
hilt = "2.51.1"
jetbrainsKotlinJvm = "1.9.24"
junit = "4.13.2"
jvmTarget = "17"
kotlin = "1.9.24"
kotlinxCoroutines = "1.8.1"
ksp = "1.9.24-1.0.20"
ktor = "2.3.12"
material = "1.12.0"
minSdk = "26"
okhttp = "4.12.0"
retrofit = "2.11.0"
room = "2.6.1"
serialization = "1.6.3"
supabase = "2.5.1"
targetSdk = "34"
versionCode = "1"
versionName = "0.0.1"

[libraries]
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }
androidxComposeBom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidxComposeMaterial3 = { group = "androidx.compose.material3", name = "material3" }
androidxComposeUiTooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidxComposeUiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidxHiltNavigationCompose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHilt" }
androidxLifecycleRuntimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidxNavigationCompose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidxTestEspressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }
androidxTestExtJunitKtx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
coilCompose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
hiltAndroid = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hiltCompiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hiltCore = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinxCoroutinesCore = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
ktor = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttpLogging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofitConverterSerialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }
roomCompiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
roomKtx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
roomRuntime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
supabaseBom = { group = "io.github.jan-tennert.supabase", name = "bom", version.ref = "supabase" }
supabasePostgrestKt = { group = "io.github.jan-tennert.supabase", name = "postgrest-kt", version.ref = "supabase" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
hiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
javaLibrary = { id = "java-library" }
jetbrainsKotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
